services:
  - type: web
    name: authentik-server
    env: docker
    plan: free
    image:
      url: ghcr.io/goauthentik/server:latest
    dockerCommand: server
    envVars:
      - key: AUTHENTIK_SECRET_KEY
        sync: false
      - key: AUTHENTIK_POSTGRESQL__HOST
        fromDatabase:
          name: postgresql
          property: host
      - key: AUTHENTIK_POSTGRESQL__NAME
        value: authentik
      - key: AUTHENTIK_POSTGRESQL__USER
        value: authentik
      - key: AUTHENTIK_POSTGRESQL__PASSWORD
        fromDatabase:
          name: postgresql
          property: password

  - type: worker
    name: authentik-worker
    env: docker
    plan: free
    image:
      url: ghcr.io/goauthentik/server:latest
    dockerCommand: worker
    envVars:
      - key: AUTHENTIK_SECRET_KEY
        sync: false
      - key: AUTHENTIK_POSTGRESQL__HOST
        fromDatabase:
          name: postgresql
          property: host
      - key: AUTHENTIK_POSTGRESQL__NAME
        value: authentik
      - key: AUTHENTIK_POSTGRESQL__USER
        value: authentik
      - key: AUTHENTIK_POSTGRESQL__PASSWORD
        fromDatabase:
          name: postgresql
          property: password

databases:
  - name: postgresql
    plan: free
